[2022-12-16 13:03:46,970] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:05:00+00:00 [queued]>
[2022-12-16 13:03:47,116] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:05:00+00:00 [queued]>
[2022-12-16 13:03:47,117] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 13:03:47,117] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 13:03:47,117] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 13:03:47,349] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-16 12:05:00+00:00
[2022-12-16 13:03:47,385] {standard_task_runner.py:52} INFO - Started process 3936 to run task
[2022-12-16 13:03:47,410] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-16T12:05:00+00:00', '--job-id', '1949', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpwbuc1f5u', '--error-file', '/tmp/tmp1m7mkmz2']
[2022-12-16 13:03:47,411] {standard_task_runner.py:80} INFO - Job 1949: Subtask create_table
[2022-12-16 13:03:47,984] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:05:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 13:03:49,120] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T12:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-16T12:05:00+00:00
[2022-12-16 13:03:49,282] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 13:03:49,349] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 13:03:49,367] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 13:03:50,061] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221216T120500, start_date=20221216T130346, end_date=20221216T130350
[2022-12-16 13:03:50,289] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 13:03:51,025] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
