[2022-12-12 18:42:51,813] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T20:01:00+00:00 [queued]>
[2022-12-12 18:42:51,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T20:01:00+00:00 [queued]>
[2022-12-12 18:42:51,898] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:42:51,901] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:42:51,904] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:42:52,054] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 20:01:00+00:00
[2022-12-12 18:42:52,098] {standard_task_runner.py:52} INFO - Started process 1425 to run task
[2022-12-12 18:42:52,130] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T20:01:00+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpzmv0emt4', '--error-file', '/tmp/tmphj8107pz']
[2022-12-12 18:42:52,138] {standard_task_runner.py:80} INFO - Job 593: Subtask create_table
[2022-12-12 18:42:52,938] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T20:01:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:42:53,533] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T20:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T20:01:00+00:00
[2022-12-12 18:42:53,572] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:42:53,615] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 18:42:53,633] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 18:42:53,754] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T200100, start_date=20221212T184251, end_date=20221212T184253
[2022-12-12 18:42:53,923] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:42:54,682] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
