[2022-12-16 08:04:26,061] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:01:00+00:00 [queued]>
[2022-12-16 08:04:27,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:01:00+00:00 [queued]>
[2022-12-16 08:04:27,927] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:04:27,927] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:04:27,927] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:04:29,783] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:01:00+00:00
[2022-12-16 08:04:30,402] {standard_task_runner.py:52} INFO - Started process 16661 to run task
[2022-12-16 08:04:30,619] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:01:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpqz4cznhd', '--error-file', '/tmp/tmp2b0fgg7t']
[2022-12-16 08:04:30,638] {standard_task_runner.py:80} INFO - Job 52: Subtask create_table
[2022-12-16 08:04:51,095] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:01:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:05:03,693] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:01:00+00:00
[2022-12-16 08:05:08,212] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:05:09,954] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 08:05:10,482] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 08:05:17,331] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T170100, start_date=20221216T080426, end_date=20221216T080517
[2022-12-16 08:05:22,729] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-16 08:05:24,169] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 16661. PIDs of all processes in the group: [16661]
[2022-12-16 08:05:24,199] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 16661
[2022-12-16 08:05:24,303] {process_utils.py:75} INFO - Process psutil.Process(pid=16661, status='terminated', exitcode=0, started='08:04:29') (16661) terminated with exit code 0
