[2022-12-16 10:48:14,778] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T23:20:00+00:00 [queued]>
[2022-12-16 10:48:15,540] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T23:20:00+00:00 [queued]>
[2022-12-16 10:48:15,540] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:48:15,540] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 10:48:15,540] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:48:16,285] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 23:20:00+00:00
[2022-12-16 10:48:16,399] {standard_task_runner.py:52} INFO - Started process 2265 to run task
[2022-12-16 10:48:16,619] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T23:20:00+00:00', '--job-id', '1200', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpftjlz93c', '--error-file', '/tmp/tmp_9mvinsa']
[2022-12-16 10:48:16,620] {standard_task_runner.py:80} INFO - Job 1200: Subtask create_table
[2022-12-16 10:48:18,122] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T23:20:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 10:48:20,418] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T23:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T23:20:00+00:00
[2022-12-16 10:48:20,734] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 10:48:20,850] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 10:48:20,907] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 10:48:21,995] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T232000, start_date=20221216T104814, end_date=20221216T104821
[2022-12-16 10:48:23,067] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
