[2022-12-12 18:25:21,660] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:25:21,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:25:21,746] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:21,747] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:25:21,748] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:21,913] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 16:54:00+00:00
[2022-12-12 18:25:21,929] {standard_task_runner.py:52} INFO - Started process 302 to run task
[2022-12-12 18:25:21,954] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T16:54:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp0e0zchrm', '--error-file', '/tmp/tmpfxy7qlgr']
[2022-12-12 18:25:21,960] {standard_task_runner.py:80} INFO - Job 47: Subtask create_table
[2022-12-12 18:25:22,272] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [running]> on host a49e44ee4a94
[2022-12-12 18:25:22,696] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:54:00+00:00
[2022-12-12 18:25:22,741] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:25:22,779] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 18:25:22,791] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 18:25:22,912] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T165400, start_date=20221212T182521, end_date=20221212T182522
[2022-12-12 18:25:22,995] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:25:23,220] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-12 18:38:36,801] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:38:36,954] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:38:36,960] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:36,963] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:38:36,965] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:37,154] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 16:54:00+00:00
[2022-12-12 18:38:37,279] {standard_task_runner.py:52} INFO - Started process 272 to run task
[2022-12-12 18:38:37,312] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T16:54:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpx319cd48', '--error-file', '/tmp/tmpcxtd965p']
[2022-12-12 18:38:37,327] {standard_task_runner.py:80} INFO - Job 36: Subtask create_table
[2022-12-12 18:38:38,135] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T16:54:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:38:39,198] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:54:00+00:00
[2022-12-12 18:38:39,396] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:38:39,442] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 18:38:39,452] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 18:38:39,836] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T165400, start_date=20221212T183836, end_date=20221212T183839
[2022-12-12 18:38:40,005] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:38:40,381] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
