[2022-12-12 18:40:24,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T18:05:00+00:00 [queued]>
[2022-12-12 18:40:24,411] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T18:05:00+00:00 [queued]>
[2022-12-12 18:40:24,415] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:40:24,417] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:40:24,419] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:40:24,532] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 18:05:00+00:00
[2022-12-12 18:40:24,559] {standard_task_runner.py:52} INFO - Started process 711 to run task
[2022-12-12 18:40:24,588] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T18:05:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp8p78vyzd', '--error-file', '/tmp/tmpymtbvq3m']
[2022-12-12 18:40:24,607] {standard_task_runner.py:80} INFO - Job 247: Subtask create_table
[2022-12-12 18:40:24,917] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T18:05:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:40:25,335] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T18:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T18:05:00+00:00
[2022-12-12 18:40:25,498] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:40:25,553] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 18:40:25,559] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 18:40:25,660] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T180500, start_date=20221212T184024, end_date=20221212T184025
[2022-12-12 18:40:25,790] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:40:25,912] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
