[2022-12-15 17:01:01,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [queued]>
[2022-12-15 17:01:01,644] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [queued]>
[2022-12-15 17:01:01,646] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-15 17:01:01,647] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-15 17:01:01,648] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-15 17:01:01,671] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:00:00+00:00
[2022-12-15 17:01:01,678] {standard_task_runner.py:52} INFO - Started process 314 to run task
[2022-12-15 17:01:01,682] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpv7goa8ru', '--error-file', '/tmp/tmpj5jvbauf']
[2022-12-15 17:01:01,684] {standard_task_runner.py:80} INFO - Job 30: Subtask create_table
[2022-12-15 17:01:01,828] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [running]> on host 39e562fe01ff
[2022-12-15 17:01:01,975] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:00:00+00:00
[2022-12-15 17:01:01,993] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-15 17:01:02,000] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-15 17:01:02,003] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-15 17:01:02,024] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T170000, start_date=20221215T170101, end_date=20221215T170102
[2022-12-15 17:01:02,057] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-15 17:01:02,122] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-16 08:01:59,807] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [queued]>
[2022-12-16 08:02:11,462] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [queued]>
[2022-12-16 08:02:12,406] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:02:13,016] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:02:13,628] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:02:24,154] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:00:00+00:00
[2022-12-16 08:02:24,523] {standard_task_runner.py:52} INFO - Started process 16638 to run task
[2022-12-16 08:02:26,478] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpsielt9z4', '--error-file', '/tmp/tmpzksk0ftz']
[2022-12-16 08:02:26,721] {standard_task_runner.py:80} INFO - Job 43: Subtask create_table
[2022-12-16 08:03:00,265] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:00:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:03:16,478] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:00:00+00:00
[2022-12-16 08:03:19,773] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:03:20,361] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 08:03:20,546] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 08:03:26,005] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T170000, start_date=20221216T080200, end_date=20221216T080326
[2022-12-16 08:03:27,983] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 08:03:37,058] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
