[2022-12-12 18:39:53,406] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T17:42:00+00:00 [queued]>
[2022-12-12 18:39:53,503] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T17:42:00+00:00 [queued]>
[2022-12-12 18:39:53,507] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:53,510] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:39:53,512] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:53,630] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 17:42:00+00:00
[2022-12-12 18:39:53,647] {standard_task_runner.py:52} INFO - Started process 567 to run task
[2022-12-12 18:39:53,714] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T17:42:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp68jr1sw0', '--error-file', '/tmp/tmp_ivi0e_u']
[2022-12-12 18:39:53,724] {standard_task_runner.py:80} INFO - Job 177: Subtask create_table
[2022-12-12 18:39:54,429] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T17:42:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:39:54,965] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T17:42:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T17:42:00+00:00
[2022-12-12 18:39:55,048] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:39:55,073] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 18:39:55,080] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 18:39:55,672] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T174200, start_date=20221212T183953, end_date=20221212T183955
[2022-12-12 18:39:55,817] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:39:56,373] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
