[2022-12-12 18:25:57,543] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [queued]>
[2022-12-12 18:25:57,860] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [queued]>
[2022-12-12 18:25:57,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:57,878] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:25:57,880] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:58,251] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 17:08:00+00:00
[2022-12-12 18:25:58,298] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2022-12-12 18:25:58,304] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T17:08:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpzkff3dmj', '--error-file', '/tmp/tmpnr9lpkky']
[2022-12-12 18:25:58,322] {standard_task_runner.py:80} INFO - Job 118: Subtask transfer_data
[2022-12-12 18:25:58,552] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [running]> on host a49e44ee4a94
[2022-12-12 18:25:59,025] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T17:08:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T17:08:00+00:00
[2022-12-12 18:25:59,086] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:25:59,159] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:25:59,317] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T170800, start_date=20221212T182557, end_date=20221212T182559
[2022-12-12 18:25:59,459] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:25:59,549] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-12 18:25:59,630] {dagrun.py:562} INFO - Marking run <DagRun prepare_data @ 2022-11-28 17:08:00+00:00: scheduled__2022-11-28T17:08:00+00:00, externally triggered: False> successful
[2022-12-12 18:25:59,635] {dagrun.py:622} INFO - DagRun Finished: dag_id=prepare_data, execution_date=2022-11-28 17:08:00+00:00, run_id=scheduled__2022-11-28T17:08:00+00:00, run_start_date=2022-12-12 18:25:43.012225+00:00, run_end_date=2022-12-12 18:25:59.634884+00:00, run_duration=16.622659, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2022-11-28 17:08:00+00:00, data_interval_end=2022-11-28 17:09:00+00:00, dag_hash=74eff07297e15e09abd94d4632e2b9b9
[2022-12-12 18:39:11,880] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [queued]>
[2022-12-12 18:39:11,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [queued]>
[2022-12-12 18:39:11,984] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:11,991] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:39:11,996] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:12,079] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 17:08:00+00:00
[2022-12-12 18:39:12,091] {standard_task_runner.py:52} INFO - Started process 396 to run task
[2022-12-12 18:39:12,130] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T17:08:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpxxllz15r', '--error-file', '/tmp/tmppb3ldkfp']
[2022-12-12 18:39:12,145] {standard_task_runner.py:80} INFO - Job 97: Subtask transfer_data
[2022-12-12 18:39:12,373] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T17:08:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:39:12,655] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T17:08:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T17:08:00+00:00
[2022-12-12 18:39:12,695] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:39:12,830] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:39:12,981] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T170800, start_date=20221212T183911, end_date=20221212T183912
[2022-12-12 18:39:13,103] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:39:13,313] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
