[2022-12-16 08:01:55,277] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T16:57:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2022-12-16 08:02:06,477] {local_task_job.py:101} INFO - Task is not able to be run
